<a href="https://colab.research.google.com/github/axel-sirota/operations-arrays-numpy/blob/main/module5/OperationsNumpy_Mod5Demo2_ByteSwapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Byte Representations on Numpy

Sometimes you are exchanging code between ittle endian and big endian architectures. In such a case, let's recall, in little endian machines, last byte of binary representation of the multibyte data-type is stored first. On the other hand, in big endian machines, first byte of binary representation of the multibyte data-type is stored first. For example x with a value of `0x01234567` would be saved as:

endian.jpg

**Do we care as programmers??** 

Usually not, except when we are dealing with code we may suspect will need to be compiled in different architectures. Let's see how to swap from one to the other

In [1]:
import numpy as np

arr = np.array([1, 256, 8755], dtype=np.int16)
print("arr is:")
print(arr)

arr is:
[   1  256 8755]


In [3]:
#displaying the data in memory in 
#hexadecimal form
print("\nData in memory in hexadecimal form")
print(list(map(hex,arr)))



Data in memory in hexadecimal form
['0x1', '0x100', '0x2233']


Let's swap. This operation is not inplace by default

In [4]:

#using byteswap() function to toggle between 
#low-endian and big-endian data representation
arr.byteswap(inplace=True)

array([  256,     1, 13090], dtype=int16)

Notice that we swapped on each element. Make sure you understand the swap from 8755 into 13090

In [6]:

#after applying byteswap() function
print("\nAfter applying byteswap() function, Arr is:")
print(arr)


After applying byteswap() function, Arr is:
[  256     1 13090]


Let's see the memory representation to verify it swapped corrrectly


In [7]:
print("\nData in memory in hexadecimal form")
print(list(map(hex,arr)))


Data in memory in hexadecimal form
['0x100', '0x1', '0x3322']


Success!!

A final note is that string byte arrays are not swapped

In [8]:
A = np.array([b'ceg', b'fac'])

A.byteswap()

array([b'ceg', b'fac'], dtype='|S3')

Notice it is the same!